<a href="https://colab.research.google.com/github/pawel0508/MachineLearning_UcznieNienadzorowane/blob/main/CwiczeniaMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


df = pd.DataFrame(data={'weight': [75., 78.5, 85., 91., 84.5, 83., 68.]})
df['weight_cut'] = pd.cut(df['weight'], bins=(60, 75, 80, 95), labels=['light', 'normal', 'heavy'])

pd.get_dummies(df)

light  normal  heavy
0      1       0      0
1      0       1      0
2      0       0      1
3      0       0      1
4      0       0      1
5      0       0      1
6      1       0      0

In [ ]:
df = pd.get_dummies(df)
print(df)

weight  weight_cut_light  weight_cut_normal  weight_cut_heavy
0    75.0                 1                  0                 0
1    78.5                 0                  1                 0
2    85.0                 0                  0                 1
3    91.0                 0                  0                 1
4    84.5                 0                  0                 1
5    83.0                 0                  0                 1
6    68.0                 1                  0                 0

In [ ]:
import pandas as pd


data_dict = {
    'currency': [['PLN', 'USD'], ['EUR', 'USD', 'PLN', 'CAD'], ['GBP'], ['JPY', 'CZK', 'HUF'], []]
}
df = pd.DataFrame(data=data_dict)




In [ ]:
df['currency'].apply(len)

0    2
1    4
2    1
3    3
4    0
Name: currency, dtype: int64

In [ ]:
import pandas as pd



df['number'] = df['currency'].apply(len)
print(df)

               currency  number
0            [PLN, USD]       2
1  [EUR, USD, PLN, CAD]       4
2                 [GBP]       1
3       [JPY, CZK, HUF]       3
4                    []       0


In [ ]:
data_dict = {
    'currency': [['PLN', 'USD'], ['EUR', 'USD', 'PLN', 'CAD'], ['GBP'], ['JPY', 'CZK', 'HUF'], []]
}
df = pd.DataFrame(data=data_dict)
df

currency
0            [PLN, USD]
1  [EUR, USD, PLN, CAD]
2                 [GBP]
3       [JPY, CZK, HUF]
4                    []

In [ ]:
df['PLN_flag'] = df['currency'].apply(lambda x: 1 if 'PLN' in x else 0)

In [ ]:
df

currency  PLN_flag
0            [PLN, USD]         1
1  [EUR, USD, PLN, CAD]         1
2                 [GBP]         0
3       [JPY, CZK, HUF]         0
4                    []         0

In [ ]:
import pandas as pd


df = pd.DataFrame(data={'hashtags': ['#good#vibes', '#hot#summer#holiday', '#street#food', '#workout']})

In [ ]:
df = df['hashtags'].str.split('#', expand = True)

In [ ]:
df = df.drop(columns = [0])

In [ ]:
df.columns = ['hastag1', 'hashtag2', 'hashtag3']

In [ ]:
import pandas as pd


df = pd.DataFrame(data={'hashtags': ['#good#vibes', '#hot#summer#holiday', '#street#food', '#workout']})
df = df['hashtags'].str.split('#', expand=True)
df = df.drop(columns=[0])
df.columns = ['hashtag1', 'hashtag2', 'hashtag3']

In [ ]:
df['missing'] = df.isnull().sum(axis = 1)

In [ ]:
df['missing'] = [df.iloc[i,].isnull().sum() for i in range(len(df))]

In [ ]:
df

hashtag1 hashtag2 hashtag3  missing
0     good    vibes     None        1
1      hot   summer  holiday        0
2   street     food     None        1
3  workout     None     None        2

hashtag1  hashtag2  hashtag3  missing
0     False     False      True     True
1     False     False     False     True
2     False     False      True     True
3     False      True      True     True

In [ ]:
import pandas as pd


df = pd.DataFrame(data={'investments': ['100_000_000', '100_000', '30_000_000', '100_500_000']})

In [ ]:
df['investments'] = [int(df.iloc[i][0].replace('_', '')) for i in range(len(df))]
print(df)

   investments
0    100000000
1       100000
2     30000000
3    100500000


In [ ]:
df = pd.DataFrame(data={'investments': ['100_000_000', '100_000', '30_000_000', '100_500_000']})

df['investments'].str.replace('_', '').astype(int)

0    100000000
1       100000
2     30000000
3    100500000
Name: investments, dtype: int64

In [ ]:
from sklearn.datasets import load_iris


In [ ]:
print(data.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [ ]:
data['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [ ]:
data_raw = load_iris()
data = data_raw['data']
target = data_raw['target']

data_train, data_test, target_train, target_test = train_test_split(data, target, test_size = 0.3)
print(f'data_train shape: {data_train.shape}')
print(f'target_train shape: {target_train.shape}')
print(f'data_test shape: {data_test.shape}')
print(f'target_test shape: {target_test.shape}')

data_train shape: (105, 4)
target_train shape: (105,)
data_test shape: (45, 4)
target_test shape: (45,)


In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


data_raw = load_iris()
data = data_raw['data']
target = data_raw['target']
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3, random_state=20)

In [2]:
import pandas as pd
import numpy as np


In [4]:
model = LogisticRegression(max_iter = 100)
model.fit(data_train, target_train)



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
from sklearn.metrics import accuracy_score
print(f'Accuracy: {accuracy_score(model.predict(data_test), target_test):.4f}')

Accuracy: 0.9333


In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
 
 
data_raw = load_iris()
data = data_raw['data']
target = data_raw['target']
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3, random_state=20)
 
model = LogisticRegression(max_iter=1000)
model.fit(data_train, target_train)
target_pred = model.predict(data_test)
print(target_pred)

[0 1 1 2 1 1 2 0 2 0 2 1 1 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 1 1 1 0 0 0 1 1
 0 1 2 1 2 0 1 1]


In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix


data_raw = load_iris()
data = data_raw['data']
target = data_raw['target']
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3, random_state=20)

model = LogisticRegression(max_iter=1000)
model.fit(data_train, target_train)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(target_test, model.predict(data_test)))

[[13  0  0]
 [ 0 18  0]
 [ 0  3 11]]
